version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Distroless.HealthChecks
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/Distroless.HealthChecks
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Distroless.HealthChecks.Test
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Distroless.Sample.WebApp
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/Distroless.Sample.WebApp
    schedule:
      interval: daily
