version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Distroless.HealthChecks
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/Distroless.HealthChecks
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Distroless.HealthChecks.Test
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Distroless.Sample.WebApp
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/Distroless.Sample.WebApp
    schedule:
      interval: daily
    ignore:
      - dependency-name: "mcr.microsoft.com/dotnet/runtime"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "mcr.microsoft.com/dotnet/nightly/runtime"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "mcr.microsoft.com/dotnet/runtime-deps"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "mcr.microsoft.com/dotnet/nightly/runtime-deps"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "mcr.microsoft.com/dotnet/aspnet"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "mcr.microsoft.com/dotnet/nightly/aspnet"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /src/Distroless.HealthChecks
    schedule:
      interval: daily
