version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Distroless.HealthChecks
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /src/Distroless.HealthChecks
    schedule:
      interval: daily
