FROM mcr.microsoft.com/dotnet/runtime-deps:10.0
FROM mcr.microsoft.com/dotnet/runtime-deps:10.0-trixie-slim
FROM mcr.microsoft.com/dotnet/runtime-deps:10.0-noble-chiseled
FROM mcr.microsoft.com/dotnet/runtime-deps:10.0-azurelinux3.0-distroless
FROM mcr.microsoft.com/dotnet/runtime-deps:10.0-alpine
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:10.0
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:10.0-trixie-slim
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:10.0-noble-chiseled
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:10.0-azurelinux3.0-distroless
FROM mcr.microsoft.com/dotnet/nightly/runtime-deps:10.0-alpine
