name: Check allowed licenses
on:
  pull_request:
    branches:
      - main
      - beta

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  CI: true

jobs:
  path-filter:
    name: Determine if workflow should run
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 2
    outputs:
      code: ${{ steps.changes.outputs.code }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        if: github.event_name != 'workflow_dispatch'
        id: changes
        with:
          filters: |-
            code:
              - '**'
              - '!**/*.md'
  check-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: >-
      (github.event_name == 'workflow_dispatch' ||
        needs.path-filter.outputs.code == 'true')
      && !cancelled()
    needs:
      - path-filter
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Setup Dotnet
        id: dotnet-setup
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: |
            10.0.x
            9.0.x
            8.0.x
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: DotNet tools restore
        run: dotnet tool restore
      - name: DotNet restore
        run: dotnet restore
      - name: Check licenses
        run: >-
          dotnet packageguard 
          --configPath allowed-licenses.json
          --github-api-key ${{ secrets.GITHUB_TOKEN }}
          ./Distroless.slnx
