name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - beta
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

permissions:
  contents: none

jobs:
  qodana:
    runs-on: ubuntu-latest
    environment: Dev
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
      checks: write
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Setup Dotnet
        id: dotnet-setup
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: |
            10.0.x
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
          persist-credentials: 'false'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@d7b5ec2fbec32197ef447c450e00589ed5f34fd5 # v2026.1.0
        with:
          pr-mode: ${{ github.event.pull_request != null }}
          args: --configuration=Release,--no-statistics=true,--linter=qodana-dotnet,--within-docker,false
          upload-result: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@e46ed2cbd01164d986452f91f178727624ae40d7 # v4.35.3
        if: ${{ !cancelled() }}
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          category: 'qodana'
