name: Release docker images
on:
  workflow_call:
    inputs:
      package:
        type: string
        required: true
      image:
        type: string
        required: true
      target:
        type: string
        required: false
      platforms:
        type: string
        required: false
        default: linux/amd64
      readme:
        type: string
        required: false
        default: ./README.md
      context:
        type: string
        required: false
        default: "."
      run:
        type: boolean
        required: false
        default: true
      semver:
        type: string
        required: false
      major:
        type: string
        required: false
      minor:
        type: string
        required: false
      tag:
        type: string
        required: false
      environment:
        description: The environment to use for the release
        type: string
        required: true
    secrets:
      DOCKERHUB_TOKEN:
        required: true

permissions: { }

jobs:
  release-docker:
    name: Release docker images
    if: ${{ inputs.run }} # this is a github limitation https://github.com/orgs/community/discussions/37883
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: ${{ inputs.environment }}
    permissions:
      contents: write # for tagging and gh release
      packages: write # for ghcr.io
      attestations: write # for attestations
      id-token: write # for tag signing
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # we use credentials to push tags below
          persist-credentials: true
      - uses: chainguard-dev/actions/setup-gitsign@dd4524afd480a43ead9543a08be1c5004ee8b0a7
      - name: Create changelog for release
        id: changelog
        run: |
          input_file="${{ inputs.package }}/CHANGELOG.md"
          output_file="/tmp/changes.md"
          # Find the line number of the first version heading
          start_line=$(grep -nE '^## [0-9]+\.[0-9]+\.[0-9]' "$input_file" | head -n 1 | cut -d: -f1)

          # Find the line number of the next version heading, if it exists
          end_line=$(grep -nE '^## [0-9]+\.[0-9]+\.[0-9]' "$input_file" | sed -n '2p' | cut -d: -f1)

          if [ -z "$end_line" ]; then
            # If there is no next version, extract till the end of the file
            sed -n "${start_line},\$p" "$input_file" > "$output_file"
          else
            # Extract only the section for the uppermost version
            sed -n "${start_line},$(($end_line-1))p" "$input_file" > "$output_file"
          fi
          echo "changes=$output_file" >> "$GITHUB_OUTPUT"
          echo "prerelease=false" >> "$GITHUB_OUTPUT"
          if [ -f ".changeset/pre.json" ]; then
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: |
            name=ghcr.io/${{ inputs.image }}
            name=docker.io/${{ inputs.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}},priority=1001
            type=raw,value=${{ inputs.major }},enable=${{ inputs.major != '' && inputs.tag == '' && inputs.major != '0'  }},priority=902
            type=raw,value=${{ inputs.major }}.${{ inputs.minor }},enable=${{ inputs.major != '' && inputs.minor != '' && inputs.tag == '' }},priority=901
            type=raw,value=${{ inputs.semver }},enable=${{ inputs.semver != '' }},priority=900
            type=edge
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
      - name: Build and push
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        id: docker_build
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.package }}/Dockerfile
          target: ${{ inputs.target }}
          platforms: ${{ inputs.platforms }}
          provenance: mode=max
          sbom: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
      - name: Attest GitHub Container Registry
        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
        with:
          subject-name: ghcr.io/${{ inputs.image }}
          subject-digest: ${{ steps.docker_build.outputs.digest }}
          push-to-registry: false
      - name: Attest Docker Hub
        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
        with:
          subject-name: docker.io/${{ inputs.image }}
          subject-digest: ${{ steps.docker_build.outputs.digest }}
          push-to-registry: false
      - name: Add docker tags and digest to release changelog
        run: |
          echo "### Digests" >> "${{ steps.changelog.outputs.changes }}"
          echo "" >> "${{ steps.changelog.outputs.changes }}"
          echo "${{ steps.meta.outputs.tags }}" | awk -v digest="${{ steps.docker_build.outputs.digest }}" '{print "- " $0 "@" digest}' >> "${{ steps.changelog.outputs.changes }}"
      - name: Tag release
        run: |
          git tag -s "${{ inputs.image }}-${{ inputs.semver }}" -m "Release ${{ inputs.image }}:${{ inputs.semver }}"
          git push origin ${{ inputs.image }}-${{ inputs.semver }}
      - name: Create GitHub release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          # files: |
          body_path: ${{ steps.changelog.outputs.changes }}
          body: Oh no, it looks like the change-notes were not generated correctly by the action.
          draft: false
          prerelease: ${{ fromJSON(steps.changelog.outputs.prerelease) }}
          generate_release_notes: true
          # fail_on_unmatched_files: true
          append_body: true
          tag_name: "${{ inputs.image }}-${{ inputs.semver }}"
          target_commitish: ${{ github.sha }}
          name: ${{ inputs.image }}:${{ inputs.semver }}
      - name: Update repo description
        if: ${{ ! fromJSON(steps.changelog.outputs.prerelease) }}
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4.0.2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ inputs.image }}
          readme-filepath: ${{ inputs.readme }}
