name: Release docker images
on:
  workflow_call:
    inputs:
      package:
        type: string
        required: true
      image:
        type: string
        required: true
      target:
        type: string
        required: false
      platforms:
        type: string
        required: false
        default: linux/amd64
      base-image-type:
        description: Base image type used by Dockerfile (e.g., ubuntu-chiseled, alpine)
        type: string
        required: false
        default: ubuntu-chiseled
      readme:
        type: string
        required: false
        default: ./README.md
      context:
        type: string
        required: false
        default: "."
      tag-suffix:
        description: Optional suffix applied to all Docker tags (e.g., -alpine)
        type: string
        required: false
        default: ""
      run:
        description: Whether to run the release job or not.
        type: boolean
        required: false
        default: true
      semver:
        type: string
        required: false
      major:
        type: string
        required: false
      minor:
        type: string
        required: false
      tag:
        type: string
        required: false
      environment:
        description: The environment to use for the release
        type: string
        required: true
    secrets:
      DOCKERHUB_TOKEN:
        required: true

permissions: { }

jobs:
  publish-digest:
    name: Build & Push image digest (${{ matrix.platform }}) - ${{ inputs.base-image-type }}${{ inputs.tag-suffix }}
    if: ${{ inputs.run }}
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    environment: ${{ inputs.environment }}
    outputs:
      # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#using-job-outputs-in-a-matrix-job
      digest-linux-amd64: ${{ steps.sanitize_platform.outputs.digest-linux-amd64 }}
      digest-linux-arm64: ${{ steps.sanitize_platform.outputs.digest-linux-arm64 }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
    permissions:
      contents: read
      # docker push
      packages: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta (labels)
        id: meta_labels
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: |
            name=ghcr.io/${{ inputs.image }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest
      - name: Get Git commit timestamp
        run: echo "GIT_TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
      - name: Build and push by digest
        id: docker_build
        if: contains(inputs.platforms, matrix.platform)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.package }}/Dockerfile
          target: ${{ inputs.target }}
          platforms: ${{ matrix.platform }}
          build-args: |
            BASE_IMAGE_TYPE=${{ inputs.base-image-type }}
          provenance: mode=max
          sbom: true
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          # tags used to select repository path for push-by-digest
          tags: ghcr.io/${{ inputs.image }}
          labels: ${{ steps.meta_labels.outputs.labels }}
          annotations: ${{ steps.meta_labels.outputs.annotations }}
        env:
          SOURCE_DATE_EPOCH: ${{ env.GIT_TIMESTAMP }}
      - name: Export digest
        if: steps.docker_build.outputs.digest != ''
        run: |
          set -euo pipefail
          dir='${{ runner.temp }}/digests-${{ inputs.base-image-type }}'
          mkdir -p "$dir"
          digest='${{ steps.docker_build.outputs.digest }}'
          # SHA-256 digests have exactly 64 hexadecimal characters after the 'sha256:' prefix
          if [[ "$digest" =~ ^sha256:([A-Fa-f0-9]{64})$ ]]; then
            fname="${BASH_REMATCH[1]}"
          else
            echo "Unexpected digest format: '$digest'" >&2
            exit 1
          fi
          touch "$dir/$fname"
      - name: Sanitize platform for artifact name
        if: steps.docker_build.outputs.digest != ''
        id: sanitize_platform
        run: |
          set -euo pipefail
          platform='${{ matrix.platform }}'
          safe=${platform//\//-}
          echo "PLATFORM_SAFE=$safe" >> "$GITHUB_ENV"
          echo "digest-$safe=${{ steps.docker_build.outputs.digest }}" >> "$GITHUB_OUTPUT"
      - name: Upload digest
        if: steps.docker_build.outputs.digest != ''
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: digests-${{ inputs.base-image-type }}-${{ env.PLATFORM_SAFE }}
          path: ${{ runner.temp }}/digests-${{ inputs.base-image-type }}/*
          if-no-files-found: error
          retention-days: 2

  test:
    name: Run tests against built digests
    if: ${{ inputs.run }}
    needs: publish-digest
    strategy:
      fail-fast: false
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/test-workflow.yml
    with:
      runs-on: ${{ matrix.platform == 'linux/arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
      healthcheck_image: ghcr.io/${{ inputs.image }}@${{ needs.publish-digest.outputs[format('digest-{0}', replace(matrix.platform, '/', '-'))]}}
      base-image-type: ${{ inputs.base-image-type }}

  merge-and-publish:
    name: Merge digest under tags (${{ inputs.base-image-type }}${{ inputs.tag-suffix }})
    if: ${{ inputs.run }}
    needs: test
    runs-on: ubuntu-24.04-arm
    environment: ${{ inputs.environment }}
    permissions:
      # docker push
      packages: write
      # attestation
      id-token: write
      attestations: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Release notes and tagging now happen in a separate job
      - name: Docker meta (tags)
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: |
            name=ghcr.io/${{ inputs.image }}
            name=docker.io/${{ inputs.image }}
          flavor: |
            suffix=${{ inputs.tag-suffix }},onlatest=true
          tags: |
            type=raw,value=latest,enable={{is_default_branch}},priority=1001
            type=raw,value=${{ inputs.major }},enable=${{ inputs.major != '' && inputs.tag == '' && inputs.major != '0'  }},priority=902
            type=raw,value=${{ inputs.major }}.${{ inputs.minor }},enable=${{ inputs.major != '' && inputs.minor != '' && inputs.tag == '' }},priority=901
            type=raw,value=${{ inputs.semver }},enable=${{ inputs.semver != '' }},priority=900
            type=edge
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
      - name: Compute tag lists (GHCR + Docker Hub)
        id: taglists
        env:
          DOCKER_METADATA_OUTPUT_JSON: ${{ steps.meta.outputs.json }}
        run: |
          set -euo pipefail
          # Extract tags for each registry once to avoid repeating jq filters
          ghcr_tags=$(jq -c '[.tags[] | select(startswith("ghcr.io/"))]' <<< "$DOCKER_METADATA_OUTPUT_JSON")
          docker_tags=$(jq -c '[.tags[] | select(startswith("docker.io/"))]' <<< "$DOCKER_METADATA_OUTPUT_JSON")
          echo "ghcr=$ghcr_tags" >> "$GITHUB_OUTPUT"
          echo "docker=$docker_tags" >> "$GITHUB_OUTPUT"
      - name: Download digests
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          path: ${{ runner.temp }}/digests-${{ inputs.base-image-type }}
          pattern: digests-${{ inputs.base-image-type }}-*
          merge-multiple: true
      - name: Create GHCR manifest list and push
        working-directory: ${{ runner.temp }}/digests-${{ inputs.base-image-type }}
        env:
          GHCR_TAGS_JSON: ${{ steps.taglists.outputs.ghcr }}
          DOCKER_METADATA_OUTPUT_JSON: ${{ steps.meta.outputs.json }}
        run: |
          set -euo pipefail
          if [ -z "$(ls -A)" ]; then
            echo "No digests found for base-image-type '${{ inputs.base-image-type }}'" >&2
            exit 1
          fi
          # Build tag and annotation args safely using arrays
          readarray -t ghcr_tags < <(jq -r '.[]' <<< "$GHCR_TAGS_JSON")
          readarray -t annotations < <(jq -r '.annotations[]?' <<< "$DOCKER_METADATA_OUTPUT_JSON")
          args=()
          for t in "${ghcr_tags[@]}"; do
            args+=( -t "$t" )
          done
          for a in "${annotations[@]}"; do
            args+=( --annotation "$a" )
          done
          # Build source refs from digest files
          sources=()
          for f in *; do
            sources+=( "ghcr.io/${{ inputs.image }}@sha256:$f" )
          done
          docker buildx imagetools create "${args[@]}" "${sources[@]}"
      - name: Inspect GHCR image
        id: inspect_ghcr
        run: |
          set -euo pipefail
          OUT=$(docker buildx imagetools inspect ghcr.io/${{ inputs.image }}:${{ steps.meta.outputs.version }})
          echo "$OUT"
          DIGEST=$(printf "%s\n" "$OUT" | sed -n 's/^Digest:\s*//p' | head -n1)
          if [ -z "$DIGEST" ]; then echo "Failed to detect manifest digest" >&2; exit 1; fi
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"
      - name: Copy manifest to Docker Hub
        env:
          DOCKER_TAGS_JSON: ${{ steps.taglists.outputs.docker }}
          DOCKER_METADATA_OUTPUT_JSON: ${{ steps.meta.outputs.json }}
        run: |
          set -euo pipefail
          mapfile -t docker_tags < <(jq -r '.[]' <<< "$DOCKER_TAGS_JSON")
          if [ "${#docker_tags[@]}" -gt 0 ]; then
            SRC="ghcr.io/${{ inputs.image }}:${{ steps.meta.outputs.version }}"
            readarray -t annotations < <(jq -r '.annotations[]?' <<< "$DOCKER_METADATA_OUTPUT_JSON")
            args=()
            for t in "${docker_tags[@]}"; do
              args+=( -t "$t" )
            done
            for a in "${annotations[@]}"; do
              args+=( --annotation "$a" )
            done
            docker buildx imagetools create "${args[@]}" "$SRC"
          else
            echo "No Docker Hub tags to publish."
          fi
      - name: Attest GHCR manifest
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-name: ghcr.io/${{ inputs.image }}
          subject-digest: ${{ steps.inspect_ghcr.outputs.digest }}
          push-to-registry: true
      - name: Attest Docker Hub manifest
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-name: docker.io/${{ inputs.image }}
          subject-digest: ${{ steps.inspect_ghcr.outputs.digest }}
          push-to-registry: true
      - name: Persist merge metadata for release job
        env:
          DOCKER_METADATA_OUTPUT_JSON: ${{ steps.meta.outputs.json }}
        run: |
          set -euo pipefail
          digest='${{ steps.inspect_ghcr.outputs.digest }}'
          printf '%s\n' "$digest" > manifest-digest.txt
          # Avoid inlining JSON into the script; read from env safely
          printf '%s' "$DOCKER_METADATA_OUTPUT_JSON" | jq -c '.' > metadata.json
          variant='${{ inputs.base-image-type }}'
          printf '%s\n' "$variant" > variant.txt
      - name: Upload merged artifact (digest + metadata)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          # Use a slash-free name for artifacts to avoid issues
          name: merged-${{ inputs.base-image-type }}
          path: |
            manifest-digest.txt
            metadata.json
            variant.txt
          retention-days: 3
